import {readFile,writeFile,mkdir} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const html=await readFile(new URL('brand-src/member.html',root),'utf8');
const assets=await readFile(new URL('brand-src/member-assets.json',root),'utf8');
const handler=await readFile(new URL('brand-src/handler.mjs',root),'utf8');
await mkdir(new URL('api/',root),{recursive:true});
await writeFile(new URL('api/bi-member.mjs',root),'// Generated by scripts/build-member.mjs. Do not serve brand-src statically.\nconst memberHtml='+JSON.stringify(html)+';\nconst memberAssets='+assets+';\n'+handler);
console.log('Member function built.');
